### ISSUE TITLE
diff reportでエラーになります

### ISSUE THREAD

**Issue by mogiken** [Sunwood-ai-labs/SourceSage#22]
下記のエラーです
タグは存在しないREPOになります

```
Traceback (most recent call last):
  File "/home/mogi/.local/bin/sourcesage", line 8, in <module>
    sys.exit(main())
  File "/home/mogi/.local/lib/python3.10/site-packages/sourcesage/cli.py", line 61, in main
    diff, latest_tag, previous_tag = git_diff_generator.get_git_diff()
  File "/home/mogi/.local/lib/python3.10/site-packages/sourcesage/modules/ReleaseDiffReportGenerator.py", line 38, in get_git_diff
    raise Exception("比較するタグが十分にありません。")
Exception: 比較するタグが十分にありません。
```

**Comment by Sunwood-ai-labs** [comment]
issuesありがとうございます。
エラーが見にくくて申し訳ないんですが、機能的には問題なく機能していると思われるので`.SourceSageAssets`を見てみてください。
タグを2つ作成してもらえばエラーの出現は無事に消えると思います！

次回のリリース辺りには見やすいように修正したいと思います

**Comment by mogiken** [comment]
フォルダーにmdがありました
とりあえずこれで試してみます
次回リリース楽しみにしています
