### ISSUE TITLE
成功する時もあるがたまに起きてしまうエラー

### ISSUE THREAD

**Issue by hayashitomoharu** [Sunwood-ai-labs/SourceSage#29]
こんにちは最近 SourceSage を知って使わさせてもらっています。
Gitの差分までプロンプトとして出力できる機能や、プロンプトとして考慮されているデータの示し方が素晴らしいと思っております👍

以下のエラーが発生しましたので報告になります。
```
Traceback (most recent call last):
  File "/home/myusername/.pyenv/versions/3.12.3/bin/sourcesage", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/myusername/.pyenv/versions/3.12.3/lib/python3.12/site-packages/sourcesage/cli.py", line 96, in main
    sourcesage.run()
  File "/home/myusername/.pyenv/versions/3.12.3/lib/python3.12/site-packages/sourcesage/core.py", line 46, in run
    changelog_generator.integrate_changelogs()
  File "/home/myusername/.pyenv/versions/3.12.3/lib/python3.12/site-packages/sourcesage/modules/ChangelogGenerator.py", line 123, in integrate_changelogs
    with open(file_path, 'r', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
- 他リポジトリでは、全て正しく出力できることもあるため、すべてのケースで失敗するわけではありません。
- 一度失敗すると再度実行しても失敗します
- 実行環境はLinuxです

すみませんが再現方法がこちらでもわかっていないので、もしわかったら追記します 🙇

**Comment by Sunwood-ai-labs** [comment]
この問題についてご報告ありがとうございます。おそらくリポジトリ内のいくつかのファイルがUTF-8でエンコードされていないことが原因だと思われます。

最新のSourceSageパッケージをインストールすることをお勧めします。最新バージョンではこの問題に対処している可能性があります。以下のコマンドを実行してアップグレードしてください:

```
pip install --upgrade sourcesage
```

もし最新版でも問題が解決しない場合は、再度エラー文などを提供していただけると助かります。再現手順がわかれば原因の特定と修正がしやすくなります。

今後ともSourceSageをよろしくお願いします。ご意見ご指摘は製品の改善に役立ちますので、お気づきの点があればぜひお知らせください。
